services:
  - name: your-nodejs-server
    type: web
    buildCommand: npm install
    startCommand: node server.js
  - name: your-vite-react-app
    type: web
    buildCommand: npm install && npm run build
    startCommand: npm run serve
